web: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --timeout 120 --log-file -
worker: celery -A config worker --loglevel=info --concurrency=4
beat: celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
channels: daphne -b 0.0.0.0 -p 8001 config.asgi:application
