# Generated by Django 4.2.13 on 2026-08-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Gooprep', max_length=100)),
                ('tagline', models.CharField(default='Learn Without Limits', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('logo_url', models.URLField(blank=True)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('support_email', models.EmailField(default='support@gooprep.com', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('timezone', models.CharField(default='Africa/Accra', max_length=50)),
                ('primary_color', models.CharField(default='#e63900', max_length=7)),
                ('secondary_color', models.CharField(default='#f5a800', max_length=7)),
                ('header_bg', models.CharField(default='#111111', max_length=7)),
                ('footer_bg', models.CharField(default='#111111', max_length=7)),
                ('link_color', models.CharField(default='#e63900', max_length=7)),
                ('button_color', models.CharField(default='#e63900', max_length=7)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('paystack_public_key', models.CharField(blank=True, max_length=200)),
                ('paystack_secret_key', models.CharField(blank=True, max_length=200)),
                ('whatsapp_api_token', models.CharField(blank=True, max_length=200)),
                ('whatsapp_phone_id', models.CharField(blank=True, max_length=100)),
                ('google_maps_api_key', models.CharField(blank=True, max_length=200)),
                ('cloudflare_account_id', models.CharField(blank=True, max_length=200)),
                ('cloudflare_access_key', models.CharField(blank=True, max_length=200)),
                ('cloudflare_secret_key', models.CharField(blank=True, max_length=200)),
                ('cloudflare_bucket', models.CharField(blank=True, max_length=100)),
                ('openai_api_key', models.CharField(blank=True, max_length=200)),
                ('guppy_app_id', models.CharField(blank=True, max_length=200)),
                ('guppy_api_key', models.CharField(blank=True, max_length=200)),
                ('guppy_webhook_secret', models.CharField(blank=True, max_length=200)),
                ('bbb_url', models.URLField(blank=True)),
                ('bbb_secret', models.CharField(blank=True, max_length=200)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=15, max_digits=4)),
                ('min_payout', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('escrow_release_hours', models.IntegerField(default=24)),
                ('cancellation_hours', models.IntegerField(default=24)),
                ('ai_enabled', models.BooleanField(default=True)),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('group_classes_enabled', models.BooleanField(default=True)),
                ('institutions_enabled', models.BooleanField(default=True)),
                ('trials_enabled', models.BooleanField(default=True)),
                ('gamification_enabled', models.BooleanField(default=True)),
                ('guppy_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms of Service'), ('about', 'About Us'), ('faq', 'FAQ'), ('how_it_works', 'How It Works'), ('ip_policy', 'IP Policy'), ('cookie', 'Cookie Policy'), ('refund', 'Refund Policy')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
