# Generated by Django 4.2.13 on 2026-08-31 07:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_alter_sitesettings_commission_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
