# Generated by Django 4.2.13 on 2026-08-05 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('review', 'Review'), ('message', 'Message'), ('profile', 'Profile'), ('other', 'Other')], max_length=20)),
                ('content_id', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('reasons', models.JSONField(default=list)),
                ('flag_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('resolution', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
