# Generated by Django 4.2.13 on 2026-08-05 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='bi-book', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=60, max_digits=8)),
                ('teaching_style', models.CharField(choices=[('interactive', 'Interactive'), ('lecture', 'Lecture'), ('socratic', 'Socratic'), ('project', 'Project-based'), ('visual', 'Visual')], default='interactive', max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_top_rated', models.BooleanField(default=False)),
                ('instant_book', models.BooleanField(default=True)),
                ('trial_lesson_enabled', models.BooleanField(default=False)),
                ('trial_lesson_price', models.DecimalField(decimal_places=2, default=30, max_digits=8)),
                ('intro_video_url', models.URLField(blank=True)),
                ('record_by_default', models.BooleanField(default=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_lessons', models.PositiveIntegerField(default=0)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('response_time', models.PositiveIntegerField(default=60)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pending_payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_paid_out', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('education', models.JSONField(default=list)),
                ('certifications', models.JSONField(default=list)),
                ('availability', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subjects', models.ManyToManyField(blank=True, related_name='tutors', to='tutors.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tutor_profiles',
            },
        ),
        migrations.CreateModel(
            name='TutorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('id', 'Government ID'), ('cert', 'Certificate'), ('degree', 'Degree'), ('other', 'Other')], max_length=10)),
                ('file', models.FileField(upload_to='tutor_docs/')),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tutors.tutorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TutorFavourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='tutors.tutorprofile')),
            ],
            options={
                'unique_together': {('student', 'tutor')},
            },
        ),
    ]
