export const GHANA_INSTITUTIONS = [
  'University of Ghana (UG)',
  'Kwame Nkrumah University of Science and Technology (KNUST)',
  'University of Cape Coast (UCC)',
  'University of Education, Winneba (UEW)',
  'University for Development Studies (UDS)',
  'University of Mines and Technology (UMaT)',
  'University of Energy and Natural Resources (UENR)',
  'University of Health and Allied Sciences (UHAS)',
  'Ghana Institute of Management and Public Administration (GIMPA)',
  'Ashesi University',
  'Central University',
  'Academic City University College',
  'Accra Technical University',
  'Kumasi Technical University',
  'Takoradi Technical University',
  'Cape Coast Technical University',
  'Koforidua Technical University',
  'Ho Technical University',
  'Sunyani Technical University',
  'Bolgatanga Technical University',
  'Tamale Technical University',
  'Ghana Institute of Journalism (GIJ)',
  'Nursing and Midwifery Training College',
  'College of Community Health Nursing',
  'Ghana College of Physicians and Surgeons',
  'Ghana College of Pharmacists',
  'Chartered Institute of Bankers (Ghana)',
  'Institute of Chartered Accountants, Ghana (ICAG)',
  'Ghana Institute of Procurement and Supply (GIPS)',
  'Other Ghanaian institution',
]
