# Generated by Django 4.2.13 on 2026-08-05 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(choices=[('regular', 'Regular'), ('trial', 'Trial'), ('group', 'Group')], default='regular', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('topic', models.CharField(blank=True, max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('bbb_meeting_id', models.CharField(blank=True, max_length=200)),
                ('bbb_join_url', models.URLField(blank=True)),
                ('record_session', models.BooleanField(default=True)),
                ('recording_available', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_flashcards', models.JSONField(default=list)),
                ('ai_quiz', models.JSONField(default=list)),
                ('has_review', models.BooleanField(default=False)),
                ('booked_on_behalf', models.BooleanField(default=False)),
                ('booker_name', models.CharField(blank=True, max_length=200)),
                ('booker_relationship', models.CharField(blank=True, max_length=50)),
                ('booker_phone', models.CharField(blank=True, max_length=30)),
                ('booker_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_lessons', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutors.subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['-start_time'],
            },
        ),
    ]
