# Generated by Django 4.2.13 on 2026-09-01 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0005_identity_documents'),
        ('scheduling', '0004_webhook_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbbwebhookevent',
            name='event_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bbbwebhookevent',
            name='meeting_id',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bbbwebhookevent',
            name='processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='bbbwebhookevent',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='ai_flashcards',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='ai_quiz',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='bbb_meeting_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='tutors.subject'),
        ),
        migrations.AddIndex(
            model_name='bbbwebhookevent',
            index=models.Index(fields=['meeting_id', 'event_type'], name='bbb_webhook_meeting_b409c4_idx'),
        ),
        migrations.AddIndex(
            model_name='bbbwebhookevent',
            index=models.Index(fields=['processed', 'received_at'], name='bbb_webhook_process_aad30a_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['tutor', 'start_time'], name='lessons_tutor_i_4b3182_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['student', 'start_time'], name='lessons_student_c8df15_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['status', 'start_time'], name='lessons_status_a82e95_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['bbb_meeting_id'], name='lessons_bbb_mee_b78607_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['payment_status'], name='lessons_payment_cc0221_idx'),
        ),
    ]
